Repository hyfi06/platzi-master-end-game-backend, pull requests merged in 2020-05, with the labels that each got.

#3 Setup initial code base server with nodejs and express
  .env.example
  .eslintrc.json
  .gitignore
  .prettierrc.json
  LICENSE
  README.md
  config/index.js
  package-lock.json
  package.json
  src/index.js
Labels: enhancement

#5 Setup CI/CD Travis and Heroku
  .travis.yml
  package.json
Labels: enhancement

#8 [FIX] Issue #7: fixed typos in .travis.yml
  .travis.yml
Labels: bug

#9 [fix] The secure of Heroku
  .travis.yml
Labels: bug

#11 [FIX] change the api key
  .travis.yml
Labels: bug

#13 Setup-mongodb-lib-service-and-route-csv-import-users
  .travis.yml
  components/users/routes.js
  components/users/usersService.js
  config/index.js
  lib/mongo.js
  package-lock.json
  package.json
  public/uploads/file.csv
  src/index.js
  utils/schema/csvSchema.js
  utils/schema/usersSchema.js
Labels: enhancement

#15 [HOTFIX] fix duplicate routes in index
  components/users/routes.js
  package.json
  src/index.js
Labels: bug

#21 [FEATURE]CRUD Users and SchemaUsers
  components/users/routes.js
  components/users/usersService.js
  lib/mongo.js
  package-lock.json
  package.json
  utils/schema/usersSchema.js
Labels: enhancement

#36 Feat exams
  components/exams/examsService.js
  components/exams/routes.js
  components/orders/ordersService.js
  components/orders/routes.js
  config/index.js
  package.json
  src/index.js
  utils/schema/README.md
  utils/schema/examsSchema.js
  utils/schema/ordersSchema.js
Labels: documentation, enhancement

#34 Auth Basic Auth Jwt implementation route and service
  .env.example
  components/auth/apiKeysService.js
  components/auth/routes.js
  components/users/routes.js
  components/users/usersService.js
  config/index.js
  package-lock.json
  package.json
  src/index.js
  utils/auth/strategies/basic.js
  utils/auth/strategies/jwt.js
  utils/middleware/errorHandler.js
  utils/schema/README.md
  utils/schema/usersSchema.js
Labels: enhancement

#37 fix(orders,exams): add passport athenticate for order and exams routes
  components/exams/routes.js
  components/orders/routes.js
  package.json
Labels: bug

#47 Feat results mocks
  components/exams/examsService.js
  components/exams/routes.js
  components/orders/ordersService.js
  components/orders/routes.js
  components/results/README.md
  components/results/resultsService.js
  components/results/routes.js
  config/index.js
  package.json
  src/index.js
  utils/middleware/validationIdHandler.js
  utils/mocks/exams.js
  utils/mocks/order.js
  utils/mocks/result.js
  utils/mocks/users.js
  utils/schema/README.md
  utils/schema/examsSchema.js
  utils/schema/ordersSchema.js
  utils/schema/resultsSchema.js
  utils/scripts/exams.js
  utils/scripts/orders.js
  utils/scripts/results.js
  utils/scripts/users.js
Labels: enhancement

#49 refactor(mongoDB): add auto createdAt and updatedAt
  lib/mongo.js
Labels: enhancement

#53 refactor: error handler use Sentry only in production
  utils/middleware/errorHandler.js
Labels: bug

#51 feat(auth): create password lib
  lib/password.js
  package.json
Labels: enhancement

#55 Test env
  package-lock.json
  package.json
  test/test.js
  utils/mocks/mongoLib.js
  utils/testServer.js
Labels: enhancement

#57 Refactor exams endpoint
  README.md
  components/exams/README.md
  components/exams/examsService.js
  components/exams/routes.js
  utils/mocks/exams.js
  utils/scripts/exams.js
Labels: documentation, enhancement

#61 Install CORS
  package-lock.json
  package.json
  src/index.js
Labels: bug

#65 Refactor endpoints exams results orders
  README.md
  components/orders/README.md
  components/orders/ordersService.js
  components/orders/routes.js
  components/results/README.md
  components/results/resultsService.js
  components/results/routes.js
  package-lock.json
  package.json
  utils/middleware/validationIdHandler.js
  utils/mocks/exams.js
  utils/mocks/order.js
  utils/mocks/result.js
  utils/mocks/users.js
  utils/schema/resultsSchema.js
  utils/scripts/orders.js
  utils/scripts/results.js
  utils/scripts/users.js
Labels: documentation, enhancement

#70 Add generate password, usernames dynamically and filters for list users
  components/users/routes.js
  components/users/usersService.js
  lib/mongo.js
  lib/password.js
  lib/username.js
  utils/scripts/apiKeys.js
Labels: enhancement

#71 Readme update
  README.md
  package.json
Labels: documentation

#72 Lib sendgrid, create service for email and template and send email
  .env.example
  components/users/usersService.js
  config/index.js
  lib/mail.js
  package-lock.json
  package.json
  utils/templates/emailTemplate.js
Labels: enhancement

#74 Add isActive field in getUsers and modify method update patch and extend duration token
  components/auth/routes.js
  components/users/routes.js
Labels: wontfix

#78 Changes default path and change getUser route
  components/auth/routes.js
  components/users/routes.js
  config/index.js
Labels: enhancement

#80 feat(pdfs): add pdf route, service and templates
  components/pdfs/pdfsService.js
  components/pdfs/routes.js
  package-lock.json
  package.json
  src/index.js
  utils/templates/resultsPDF/layout.js
  utils/templates/resultsPDF/patient.js
  utils/templates/resultsPDF/resultTest.js
  utils/templates/resultsPDF/rowtest.js
Labels: enhancement

#84 fix(orders): order routes fixed
  components/orders/routes.js
Labels: bug

#81 Change response id, username to createUser
  components/users/routes.js
  components/users/usersService.js
Labels: wontfix

#87 Validate if values in args is number and add documentId display in getUsers
  components/users/routes.js
  components/users/usersService.js
Labels: enhancement

#88 fix: upgrade @hyfi06/html2pdf
  package-lock.json
  package.json
Labels: bug

#92 Feat pdf validation
  components/pdfs/README.md
  components/pdfs/pdfsService.js
  components/pdfs/routes.js
Labels: documentation, enhancement

#94 fix(pdf): fix repeat results in pdf
  components/pdfs/pdfsService.js
Labels: bug

#98 Fix conditional on get users route
  components/users/usersService.js
Labels: enhancement

#105 fix(auth): fix default path for patients
  config/index.js
Labels: bug

#102 RegExp in filter with mongo to filter users with lowercase in names
  components/users/usersService.js
Labels: enhancement

#103 fix(orders): user friendly message for orders endpoints
  components/orders/README.md
  components/orders/ordersService.js
  components/orders/routes.js
Labels: documentation

#106 Test auth
  components/auth/routes.js
  src/index.js
  test/auth.routes.test.js
  test/auth.service.test.js
  utils/middleware/errorHandler.js
  utils/middleware/errorRegister.js
  utils/mocks/auth.js
  utils/mocks/mongoLib.js
  utils/mocks/users.js
  utils/testServer.js
Labels: enhancement

#110 Create "adding users" endpoint with csv load
  components/users/routes.js
  components/users/usersService.js
  lib/mail.js
  lib/mongo.js
  public/uploads/test.csv
  utils/mocks/mongoLib.js
  utils/schema/usersSchema.js
Labels: enhancement

#113 v1.0.0
  package-lock.json
  package.json
Labels: enhancement

#108 Add validation to isActive param query and return boolean correctly
  components/users/routes.js
  components/users/usersService.js
Labels: enhancement

#114 [ADD]Messages to user endpoints
  components/auth/routes.js
  components/users/routes.js
  components/users/usersService.js
  utils/auth/strategies/basic.js
  utils/schema/csvSchema.js
  utils/schema/usersSchema.js
Labels: enhancement

#117 fix(pdf): documentation correction
  README.md
  components/pdfs/README.md
Labels: documentation

#118 Test exams
  lib/asyncThrows.js
  test/auth.routes.test.js
  test/exams.routes.test.js
  test/exams.service.test.js
  utils/mocks/auth.js
  utils/mocks/config.js
  utils/mocks/exams.js
  utils/mocks/login.js
  utils/mocks/mongoLib.js
Labels: enhancement

#131 refactor(orders): add isComplete query
  components/orders/README.md
  components/orders/ordersService.js
  components/orders/routes.js
Labels: enhancement, help wanted

#123 fix(test): fix userServiceMock. add copy function for delete in auth
  utils/mocks/users.js
Labels: bug

#130 fix(pdf): change pdf endpoint from get to post
  components/pdfs/routes.js
Labels: bug, help wanted

#121 Add Readme users
  components/users/README.md
Labels: documentation

#135 Add messageService and route to create and get messages
  README.md
  components/messages/README.md
  components/messages/messagesService.js
  components/messages/routes.js
  config/index.js
  lib/mongo.js
  package.json
  src/index.js
  utils/schema/messagesSchema.js
Labels: enhancement

#127 Test orders
  test/exams.service.test.js
  test/orders.routes.test.js
  test/orders.service.test.js
  test/results.routes.test.js
  test/results.service.test.js
  utils/mocks/exams.js
  utils/mocks/mongoLib.js
  utils/mocks/order.js
  utils/mocks/result.js
  utils/mocks/users.js
Labels: enhancement

#125 Test results
  test/exams.service.test.js
  test/results.routes.test.js
  test/results.service.test.js
  utils/mocks/exams.js
  utils/mocks/mongoLib.js
  utils/mocks/order.js
  utils/mocks/result.js
  utils/mocks/users.js
Labels: enhancement

#138 Send emails with environment variable boolean
  .env.example
  components/users/usersService.js
  config/index.js
Labels: bug

#139 feat(messages): create messages on order created and results created
  components/orders/routes.js
  components/results/routes.js
  test/orders.routes.test.js
  test/orders.service.test.js
  test/results.routes.test.js
  utils/mocks/messages.js
Labels: enhancement

#141 test(messeages): add test of messages routes and services
  test/messages.routes.test.js
  test/messages.services.test.js
  utils/mocks/messages.js
  utils/mocks/mongoLib.js
Labels: enhancement

#142 fix(users,ordes): update the response messages
  components/orders/ordersService.js
  components/users/routes.js
Labels: bug

#143 docs(results): fix route in results documentation
  components/results/README.md
Labels: bug, documentation

#144 docs: Add logo in readme, add contribuding.md add authors
  README.md
  contributing.md
Labels: enhancement

#146 Readme authentication
  components/auth/README.md
Labels: documentation

#148 docs: add function documentation
  components/auth/apiKeysService.js
  components/exams/examsService.js
  components/messages/messagesService.js
  components/orders/ordersService.js
  components/pdfs/pdfsService.js
  components/results/resultsService.js
  components/users/usersService.js
  lib/asyncThrows.js
  lib/mail.js
  lib/mongo.js
  lib/password.js
  lib/username.js
  utils/middleware/errorHandler.js
  utils/middleware/errorRegister.js
  utils/middleware/notFoundHandler.js
  utils/middleware/validationModelHandler.js
Labels: documentation

#147 Test users
  test/user.service.test.js
  utils/mocks/config.js
  utils/mocks/mongoLib.js
Labels: documentation

#149 Wiki section
  README.md
Labels: documentation
